apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-config
data:
  ports.conf: |
    # If you just change the port or add more ports here, you will likely also
    # have to change the VirtualHost statement in
    # /etc/apache2/sites-enabled/000-default.conf
    
    Listen 8080
    
    <IfModule ssl_module>
    	Listen 8443
    </IfModule>
    
    <IfModule mod_gnutls.c>
    	Listen 8443
    </IfModule>
  000-default.conf: |
    <VirtualHost *:8080>
    	ServerName nextcloud.irminsul
    	ServerAdmin webmaster@irminsul
    	DocumentRoot /var/www/html
    	ErrorLog ${APACHE_LOG_DIR}/error.log
    	CustomLog ${APACHE_LOG_DIR}/access.log combined
    </VirtualHost>

